### ISSUE TITLE
App won't load data

### ISSUE THREAD

**Issue by owennaufaldi** [Dacredible/stock-search#1]
Hello! I am a uni student at Uni of Manchester and have been using stock-search as a basis for my first year project. A few weeks ago when I tried stock-search it has successfully loaded all the data but now it is always stuck in the loading page and when it does go to the results page, it always fails to load data. I suspect it has nothing to do with the code itself but I don't really know as it is my first time coding. Please let me know if you know what is going wrong. Thank you very much

**Comment by Dacredible** [comment]
It's probably because the backend data cannot feed to the iOS app. Since my AWS free time is going to expire, You can change all the http request to your own in order to running the app. I might move my back-end to somewhere else but I can't guarantee. Sorry about that.

**Comment by owennaufaldi** [comment]
Hi thanks for the reply. I just need it to work until tomorrow, would it expire before? And how can I change the http request to my own? Thank you so so much!

**Comment by Dacredible** [comment]
actually I just tried it yesterday, it's working

**Comment by owennaufaldi** [comment]
Yupp it's working now. Thank you very much!
